[palettes.gruvbox-light]
bg = "#fbf1c7"
bg_dim = "#f2e5bc"
bg_alt = "#e5d5ad"
fg = "#3c3836"
fg_dim = "#665c54"
red = "#9d0006"
orange = "#af3a03"
yellow = "#8f5f00"
green = "#5f650b"
aqua = "#356a4a"
blue = "#076678"
purple = "#8f3f71"
bracket = "#8f3f71"
bracket_alt = "#af3a03"
