# Rosé Pine Dawn — btop theme (light)
# Based on https://github.com/rose-pine/btop

# Main bg
theme[main_bg]="#faf4ed"

# Main text color
theme[main_fg]="#575279"

# Title color for boxes
theme[title]="#575279"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#286983"

# Background color of selected item in processes box
theme[selected_bg]="#dfdad9"

# Foreground color of selected item in processes box
theme[selected_fg]="#b4637a"

# Color of inactive/disabled text
theme[inactive_fg]="#9893a5"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#56949f"

# Cpu box outline color
theme[cpu_box]="#cecacd"

# Memory/disks box outline color
theme[mem_box]="#cecacd"

# Net up/down box outline color
theme[net_box]="#cecacd"

# Processes box outline color
theme[proc_box]="#cecacd"

# Box divider line and small boxes line color
theme[div_line]="#dfdad9"

# Temperature graph colors
theme[temp_start]="#56949f"
theme[temp_mid]="#ea9d34"
theme[temp_end]="#b4637a"

# CPU graph colors
theme[cpu_start]="#56949f"
theme[cpu_mid]="#ea9d34"
theme[cpu_end]="#b4637a"

# Mem/Disk free meter
theme[free_start]="#b4637a"
theme[free_mid]="#d7827e"
theme[free_end]="#56949f"

# Mem/Disk cached meter
theme[cached_start]="#907aa9"
theme[cached_mid]="#286983"
theme[cached_end]="#56949f"

# Mem/Disk available meter
theme[available_start]="#d7827e"
theme[available_mid]="#ea9d34"
theme[available_end]="#907aa9"

# Mem/Disk used meter
theme[used_start]="#286983"
theme[used_mid]="#56949f"
theme[used_end]="#907aa9"

# Download graph colors
theme[download_start]="#286983"
theme[download_mid]="#56949f"
theme[download_end]="#907aa9"

# Upload graph colors
theme[upload_start]="#ea9d34"
theme[upload_mid]="#d7827e"
theme[upload_end]="#b4637a"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#56949f"
theme[process_mid]="#ea9d34"
theme[process_end]="#b4637a"
