# Catppuccin Latte (https://github.com/catppuccin/btop) — light

# Main bg
theme[main_bg]="#eff1f5"

# Main text color
theme[main_fg]="#4c4f69"

# Title color for boxes
theme[title]="#4c4f69"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#1e66f5"

# Background color of selected item in processes box
theme[selected_bg]="#bcc0cc"

# Foreground color of selected item in processes box
theme[selected_fg]="#1e66f5"

# Color of inactive/disabled text
theme[inactive_fg]="#8c8fa1"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#40a02b"

# Cpu box outline color
theme[cpu_box]="#8839ef"

# Memory/disks box outline color
theme[mem_box]="#40a02b"

# Net up/down box outline color
theme[net_box]="#e64553"

# Processes box outline color
theme[proc_box]="#1e66f5"

# Box divider line and small boxes line color
theme[div_line]="#9ca0b0"

# Temperature graph colors
theme[temp_start]="#04a5e5"
theme[temp_mid]="#8839ef"
theme[temp_end]="#d20f39"

# CPU graph colors
theme[cpu_start]="#40a02b"
theme[cpu_mid]="#df8e1d"
theme[cpu_end]="#d20f39"

# Mem/Disk free meter
theme[free_start]="#8839ef"
theme[free_mid]=""
theme[free_end]="#40a02b"

# Mem/Disk cached meter
theme[cached_start]="#04a5e5"
theme[cached_mid]=""
theme[cached_end]="#1e66f5"

# Mem/Disk available meter
theme[available_start]="#fe640b"
theme[available_mid]=""
theme[available_end]="#df8e1d"

# Mem/Disk used meter
theme[used_start]="#40a02b"
theme[used_mid]=""
theme[used_end]="#d20f39"

# Download graph colors
theme[download_start]="#fe640b"
theme[download_mid]=""
theme[download_end]="#ea76cb"

# Upload graph colors
theme[upload_start]="#40a02b"
theme[upload_mid]=""
theme[upload_end]="#179299"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#04a5e5"
theme[process_mid]="#8839ef"
theme[process_end]="#ea76cb"
