[palettes.gruvbox-classic]
bg = "#282828"
bg_dim = "#1b1b1b"
bg_alt = "#3c3836"
fg = "#ebdbb2"
fg_dim = "#bdae93"
red = "#fb4934"
orange = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
aqua = "#8ec07c"
blue = "#83a598"
purple = "#d3869b"
bracket = "#d3869b"
bracket_alt = "#fe8019"
