[palettes.github-light]
bg          = "#ffffff"
bg_dim      = "#f6f8fa"
bg_alt      = "#eaeef2"
fg          = "#24292f"
fg_dim      = "#57606a"
red         = "#a40e26"
orange      = "#953800"
yellow      = "#765800"
green       = "#116329"
aqua        = "#096778"
blue        = "#0550ae"
purple      = "#6639ba"
bracket     = "#6639ba"
bracket_alt = "#0969da"
